language: node_js
node_js:
  - "7"
  - "6"
  - "5"
  - "4"
  - "iojs"
before_install:
  - 'if [ "${TRAVIS_NODE_VERSION}" != "0.9" ]; then case "$(npm --version)" in 1.*) npm install -g npm@1.4.28 ;; 2.*) npm install -g npm@2 ;; esac ; fi'
  - 'if [ "${TRAVIS_NODE_VERSION}" != "0.6" ] && [ "${TRAVIS_NODE_VERSION}" != "0.9" ]; then npm install -g npm; fi'
before_script:
  - 'if [ -n "${REACT-}" ]; then sh install-relevant-react.sh; fi'
script:
  - 'if [ -n "${TEST-}" ]; then npm run tests-only ; fi'
sudo: false
env:
  - TEST=true REACT=15
matrix:
  fast_finish: true
  include:
    - node_js: "node"
  allow_failures:
    - node_js: "iojs"
